### ISSUE TITLE
Import of pygtide fails

### ISSUE THREAD

**Issue by emolch** [hydrogeoscience/pygtide#14]
Hi,

I am trying to run pygtide but import of the module fails:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import pygtide
  File "/home/heimann/Temp/pygtide/pygtide/__init__.py", line 1, in <module>
    from .pygtide import pygtide
  File "/home/heimann/Temp/pygtide/pygtide/pygtide.py", line 96, in <module>
    from etpred import etpred
  File "/home/heimann/Temp/pygtide/etpred/__init__.py", line 1, in <module>
    from . import etpred
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory
```

Apparently there are some compiled objects in the repos. Are these there on purpose? Is there a way to compile them for myself on my machine?

Thanks
Sebastian Heimann

**Comment by emolch** [comment]
Is the updated and f2py-compliant variant of eterna available somewhere?

**Comment by hydrogeoscience** [comment]
Unfortunately, I cannot share the Fortran source code because I don't own the copyright.

**Comment by hydrogeoscience** [comment]
Please see the new update.
