### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by hugmarc** [hydrogeoscience/pygtide#15]
Hi
Unfortunately, I get a similar error as #13. I am using anaconda 3.7 and after running test.py I get the following error: "ImportError: DLL load failed: The specified module could not be found". (see output below). Do you have any explanation for this error?
Thanks a lot for your reply

-----------------
runfile('C:/Users/hugmarc/Desktop/pygtide3/test.py', wdir='C:/Users/hugmarc/Desktop/pygtide3')
Traceback (most recent call last):
File "<ipython-input-2-2c311b341835>", line 1, in <module>
    runfile('C:/Users/hugmarc/Desktop/pygtide3/test.py', wdir='C:/Users/hugmarc/Desktop/pygtide3')

File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

File "C:/Users/hugmarc/Desktop/pygtide3/test.py", line 2, in <module>
    import pygtide

File "C:\Users\hugmarc\Desktop\pygtide3\pygtide\__init__.py", line 1, in <module>
    from .pygtide import pygtide

File "C:\Users\hugmarc\Desktop\pygtide3\pygtide\pygtide.py", line 96, in <module>
    from etpred import etpred

File "C:\ProgramData\Anaconda3\lib\site-packages\etpred\__init__.py", line 1, in <module>
    from . import etpred

ImportError: DLL load failed: The specified module could not be found.
----------------

**Comment by hydrogeoscience** [comment]
Please see the new update.
