### ISSUE TITLE
Circular Import Error

### ISSUE THREAD

**Issue by wg1562** [hydrogeoscience/pygtide#17]
I'm trying with Python v3.8.1 (Windows 10) and I'm getting a "circular import" error (see below). 

I then tried with Anaconda with v3.6 and got the same "missing DLL" error as described in other issues. Any ideas to solve this? 

 ```
python test.py
Traceback (most recent call last):
 File "test.py", line 2, in <module>
    import pygtide
  File "C:\Shared Software\pygtide-master\pygtide\__init__.py", line 1, in <module>
    from .pygtide import pygtide
  File "C:\Shared Software\pygtide-master\pygtide\pygtide.py", line 96, in <module>
    from etpred import etpred
  File "C:\Shared Software\pygtide-master\etpred\__init__.py", line 1, in <module>
    from . import etpred
ImportError: cannot import name 'etpred' from partially initialized module 'etpred' (most likely due to a circular import) (C:\pygtide-master\etpred\__init__.py)```

**Comment by hydrogeoscience** [comment]
Please see the new update.
